"""都道府県マスタ（静的シード）。"""

from __future__ import annotations

PREFECTURES: list[dict[str, str]] = [
    {"code": "01", "name_ja": "北海道", "name_en": "Hokkaido", "slug": "hokkaido"},
    {"code": "02", "name_ja": "青森県", "name_en": "Aomori Prefecture", "slug": "aomori"},
    {"code": "03", "name_ja": "岩手県", "name_en": "Iwate Prefecture", "slug": "iwate"},
    {"code": "04", "name_ja": "宮城県", "name_en": "Miyagi Prefecture", "slug": "miyagi"},
    {"code": "05", "name_ja": "秋田県", "name_en": "Akita Prefecture", "slug": "akita"},
    {"code": "06", "name_ja": "山形県", "name_en": "Yamagata Prefecture", "slug": "yamagata"},
    {"code": "07", "name_ja": "福島県", "name_en": "Fukushima Prefecture", "slug": "fukushima"},
    {"code": "08", "name_ja": "茨城県", "name_en": "Ibaraki Prefecture", "slug": "ibaraki"},
    {"code": "09", "name_ja": "栃木県", "name_en": "Tochigi Prefecture", "slug": "tochigi"},
    {"code": "10", "name_ja": "群馬県", "name_en": "Gunma Prefecture", "slug": "gunma"},
    {"code": "11", "name_ja": "埼玉県", "name_en": "Saitama Prefecture", "slug": "saitama"},
    {"code": "12", "name_ja": "千葉県", "name_en": "Chiba Prefecture", "slug": "chiba"},
    {"code": "13", "name_ja": "東京都", "name_en": "Tokyo", "slug": "tokyo"},
    {"code": "14", "name_ja": "神奈川県", "name_en": "Kanagawa Prefecture", "slug": "kanagawa"},
    {"code": "15", "name_ja": "新潟県", "name_en": "Niigata Prefecture", "slug": "niigata"},
    {"code": "16", "name_ja": "富山県", "name_en": "Toyama Prefecture", "slug": "toyama"},
    {"code": "17", "name_ja": "石川県", "name_en": "Ishikawa Prefecture", "slug": "ishikawa"},
    {"code": "18", "name_ja": "福井県", "name_en": "Fukui Prefecture", "slug": "fukui"},
    {"code": "19", "name_ja": "山梨県", "name_en": "Yamanashi Prefecture", "slug": "yamanashi"},
    {"code": "20", "name_ja": "長野県", "name_en": "Nagano Prefecture", "slug": "nagano"},
    {"code": "21", "name_ja": "岐阜県", "name_en": "Gifu Prefecture", "slug": "gifu"},
    {"code": "22", "name_ja": "静岡県", "name_en": "Shizuoka Prefecture", "slug": "shizuoka"},
    {"code": "23", "name_ja": "愛知県", "name_en": "Aichi Prefecture", "slug": "aichi"},
    {"code": "24", "name_ja": "三重県", "name_en": "Mie Prefecture", "slug": "mie"},
    {"code": "25", "name_ja": "滋賀県", "name_en": "Shiga Prefecture", "slug": "shiga"},
    {"code": "26", "name_ja": "京都府", "name_en": "Kyoto Prefecture", "slug": "kyoto"},
    {"code": "27", "name_ja": "大阪府", "name_en": "Osaka Prefecture", "slug": "osaka"},
    {"code": "28", "name_ja": "兵庫県", "name_en": "Hyogo Prefecture", "slug": "hyogo"},
    {"code": "29", "name_ja": "奈良県", "name_en": "Nara Prefecture", "slug": "nara"},
    {"code": "30", "name_ja": "和歌山県", "name_en": "Wakayama Prefecture", "slug": "wakayama"},
    {"code": "31", "name_ja": "鳥取県", "name_en": "Tottori Prefecture", "slug": "tottori"},
    {"code": "32", "name_ja": "島根県", "name_en": "Shimane Prefecture", "slug": "shimane"},
    {"code": "33", "name_ja": "岡山県", "name_en": "Okayama Prefecture", "slug": "okayama"},
    {"code": "34", "name_ja": "広島県", "name_en": "Hiroshima Prefecture", "slug": "hiroshima"},
    {"code": "35", "name_ja": "山口県", "name_en": "Yamaguchi Prefecture", "slug": "yamaguchi"},
    {"code": "36", "name_ja": "徳島県", "name_en": "Tokushima Prefecture", "slug": "tokushima"},
    {"code": "37", "name_ja": "香川県", "name_en": "Kagawa Prefecture", "slug": "kagawa"},
    {"code": "38", "name_ja": "愛媛県", "name_en": "Ehime Prefecture", "slug": "ehime"},
    {"code": "39", "name_ja": "高知県", "name_en": "Kochi Prefecture", "slug": "kochi"},
    {"code": "40", "name_ja": "福岡県", "name_en": "Fukuoka Prefecture", "slug": "fukuoka"},
    {"code": "41", "name_ja": "佐賀県", "name_en": "Saga Prefecture", "slug": "saga"},
    {"code": "42", "name_ja": "長崎県", "name_en": "Nagasaki Prefecture", "slug": "nagasaki"},
    {"code": "43", "name_ja": "熊本県", "name_en": "Kumamoto Prefecture", "slug": "kumamoto"},
    {"code": "44", "name_ja": "大分県", "name_en": "Oita Prefecture", "slug": "oita"},
    {"code": "45", "name_ja": "宮崎県", "name_en": "Miyazaki Prefecture", "slug": "miyazaki"},
    {"code": "46", "name_ja": "鹿児島県", "name_en": "Kagoshima Prefecture", "slug": "kagoshima"},
    {"code": "47", "name_ja": "沖縄県", "name_en": "Okinawa Prefecture", "slug": "okinawa"},
]

PREFECTURE_BY_CODE = {item["code"]: item for item in PREFECTURES}
